name: 🧠 Collect Codebreaker Scores
on:
  issues:
    types: [opened, labeled]

jobs:
  collect:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, 'codebreaker-win')
    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 🧩 Parse issue details
        id: parse
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "ISSUE_URL=${{ github.event.issue.html_url }}" >> $GITHUB_ENV
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 📝 Append score to SCORES.md
        run: |
          SCORES_FILE="SCORES.md"
          if [ ! -f "$SCORES_FILE" ]; then
            echo "# 🧠 Codebreaker Leaderboard" > "$SCORES_FILE"
            echo "" >> "$SCORES_FILE"
          fi

          echo "## Entry - Issue #${ISSUE_NUMBER}" >> "$SCORES_FILE"
          echo "- **Title:** ${ISSUE_TITLE}" >> "$SCORES_FILE"
          echo "- **URL:** ${ISSUE_URL}" >> "$SCORES_FILE"
          echo "- **Timestamp:** $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$SCORES_FILE"
          echo "- **Details:**" >> "$SCORES_FILE"
          echo '```' >> "$SCORES_FILE"
          echo "${ISSUE_BODY}" >> "$SCORES_FILE"
          echo '```' >> "$SCORES_FILE"
          echo "" >> "$SCORES_FILE"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$SCORES_FILE"
          git commit -m "🏁 Add Codebreaker score from issue #${ISSUE_NUMBER}" || echo "No new scores"
          git push
